# Generated by Django 3.1.7 on 2021-03-27 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyboardName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyboardname', models.CharField(max_length=255)),
                ('dateentered', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('keyboardurl', models.URLField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'keyboardname',
            },
        ),
        migrations.CreateModel(
            name='KeyboardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=255)),
                ('typedescription', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'keyboardtype',
            },
        ),
        migrations.CreateModel(
            name='KeyboardReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateentered', models.DateField()),
                ('keyboardimage', models.URLField()),
                ('keyboardreview', models.TextField()),
                ('keyboardname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyboard.keyboardname')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'keyboardimage',
            },
        ),
        migrations.AddField(
            model_name='keyboardname',
            name='keyboardtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='keyboard.keyboardtype'),
        ),
        migrations.AddField(
            model_name='keyboardname',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
